[package]
name = "webex"
version = "0.2.1"
authors = ["Scott Hutton <shutton@pobox.com>"]
edition = "2018"
description = "Interface to Webex Teams REST and WebSocket APIs"
keywords = ["webex", "spark"]
categories = ["asynchronous"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/shutton/webex-rust.git"

[dependencies]
async-std = "1.5.0"
error-chain = "0.12.2"
futures = "0.3.4"
futures-util = "0.3.4"
hyper = "0.13"
hyper-tls = "0.4.1"
log = "0.4"
serde_json = "1.0"
tokio-tls = "0.3.0"
tungstenite = "0.10.1"
url = "2.1.1"
base64 = "0.13.0"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.serde]
version = "1.0.106"
features = ["derive"]

[dependencies.tokio]
version = "0.2.16"
features = ["time", "stream", "fs", "macros", "uds", "io-util"]

[dependencies.tokio-tungstenite]
version = "0.10.1"
features = ["tls"]

[dependencies.uuid]
version = "0.8"
features = ["v4"]
